### ISSUE TITLE
Not sure what I am doing wrong

### ISSUE THREAD

**Issue by hansaliyad1** [Viima/jquery-comments#45] opened 2016-03-24 13:58 UTC
`Unhandled rejection Error: isEnabledTest requires both the host and hostData
    at chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:949:24
    at tryCatcher (chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:5624:26)
    at Function.Promise.attempt.Promise.try (chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:3069:27)
    at handleIncomingResponse (chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:941:26)
    at Object.handleMessage (chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:1024:19)
    at chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:854:15
    at EventImpl.dispatchToListener (extensions::event_bindings:387:22)
    at Event.publicClass.(anonymous function) [as dispatchToListener] (extensions::utils:94:26)
    at EventImpl.dispatch_ (extensions::event_bindings:371:35)
    at EventImpl.dispatch (extensions::event_bindings:393:17)
    at Event.publicClass.(anonymous function) [as dispatch] (extensions::utils:94:26)
    at dispatchOnMessage (extensions::messaging:320:22)`

`Unhandled rejection Error: isEnabledTest requires both the host and hostData
    at chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:949:24
    at tryCatcher (chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:5624:26)
    at Function.Promise.attempt.Promise.try (chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:3069:27)
    at handleIncomingResponse (chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:941:26)
    at Object.handleMessage (chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:1024:19)
    at chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:854:15
    at EventImpl.dispatchToListener (extensions::event_bindings:387:22)
    at Event.publicClass.(anonymous function) [as dispatchToListener] (extensions::utils:94:26)
    at EventImpl.dispatch_ (extensions::event_bindings:371:35)
    at EventImpl.dispatch (extensions::event_bindings:393:17)
    at Event.publicClass.(anonymous function) [as dispatch] (extensions::utils:94:26)
    at dispatchOnMessage (extensions::messaging:320:`

I really liked your plugin and I really appreciate for sharing with us. I just integrate it to my project with all dependencies installed and linked. But still I am getting this errors in web browser console. Can you please help me with this?

Thank you in advance.

**Comment by jessenieminen** [comment] 2016-03-24 18:43
That error looks like an issue with some of your Chrome extensions. Have you tried on a different browser and/or after disabling all Chrome plugins temporarily?

**Comment by hansaliyad1** [comment] 2016-03-24 18:44
I tried on different browser. The Demo file works well in same browser.

**Comment by jessenieminen** [comment] 2016-03-24 18:50
Well what were the error messages like in that other browser? Are any of the lines of the library referenced anywhere in the stack trace of  these errors? Can you also reproduce the issue in a CodePen or similar to try to narrow down the issue? Do these errors break some of the functionality of the library?

**Comment by jessenieminen** [comment] 2016-04-15 07:04
Since we haven't received any other reports of this behaviour and haven't still been able to replicate the issue, I'll close this issue for now. 

@hansaliyad1: If you can provide us with instructions that allow us to replicate this issue, feel free to reopen this or create another one.

**Closed** 2016-04-15 07:05 UTC
